---
language: ruby
addons:
  firefox: "36.0.1"
rvm:
  - 1.9.3
  - 2.2.0
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - cd ruby
  - bundle install
  - bundle exec rake spec
